### ISSUE TITLE
data-attributes -> dataset

### ISSUE THREAD

**Issue by caperaven** [b-fuze/deno-dom#112]
I would like to use this library to help mocking out the dom for deno tests.
It seems like dataset properties are not supported?

```
    const h1 = document.querySelector("h1");
    h1.setAttribute("data-test", "test");
    const result = h1.dataset.test;
```

dataset seems to be undefined in the element.

**Comment by b-fuze** [comment]
Yeah. Dataset looks like it probably needs to be a `Proxy`... I'll get to work on it soon

**Comment by jdoleary** [comment]
In the meantime, you can use `element.attributes.getNamedItem('data-MYVALUE')?.value;` to access data attributes.

**Comment by oscarotero** [comment]
No rush (I really appreciate all the work done in this awesome library), but I would like to know if there are plans to implement this feature anytime soon.

This issue prevents to use the latest version of highlight.js, because it uses`dataset` [to store some data](https://github.com/highlightjs/highlight.js/blob/f47103d4f1ac1592c56904574d1fbf5bf2475605/src/highlight.js#L777) and it fails.

**Comment by b-fuze** [comment]
Yeah, I got an implementation ready

**Comment by oscarotero** [comment]
thanks so much!
