### ISSUE TITLE
Add Packaging info to cargo.toml file ?

### ISSUE THREAD

**Issue by reyman** [b-fuze/deno-dom#134]
Hi !

I'm trying to packaging Deno (finished) to use with Quarto project (work in progress) for GUIX system.

Quarto project use _Deno-dom_ as dependencies https://github.com/quarto-dev/quarto-cli/blob/main/configuration#L12 

Actually i have some problem to package Quarto into Guix package because "deno-dom" is defined as a _virtual-manifest_ ... 

Is there some possibility to add some package line to cargo.toml to facilitate future packaging with application ?

Thanks !

**Comment by b-fuze** [comment]
I'm not familiar with Guix, what would need to be done to solve your issue?

**Comment by reyman** [comment]
@b-fuze Guix work by importing "crates" from the official repository (https://crates.io/) perhaps it's possible to publish deno-dom ?

**Comment by b-fuze** [comment]
The reason that I wouldn't do that is because Deno DOM is not a Rust package. It has a Rust component, but it is primarily a TypeScript Deno library.

What I'd suggest instead is to look at the [`deno vendor`](https://deno.land/manual@v1.31.1/tools/vendor) command, and also grabbing the native binary from [here](https://github.com/b-fuze/deno-dom/releases/tag/) if you're using the native Deno DOM backend.

**Comment by reyman** [comment]
Ok thanks for clarification,  i understand why Deno Dom is not a Rust Package, this is more clear. 

I cannot use directly Binary with Guix. This distribution is oriented to reproducibility, this is why everything is compiled from source. 

I see source file seems already included/pushed into quarto cli ( https://github.com/quarto-dev/quarto-cli/tree/main/src/vendor/deno.land/x ) This is not a good pratice, so i will provide vendor directly from this repository.

I will look more in depth later
