### ISSUE TITLE
Any Plans To Add text/xml Support?

### ISSUE THREAD

**Issue by ebebbington** [b-fuze/deno-dom#15]

**Comment by b-fuze** [comment]
Deno DOM is primarily focused on HTML parsing, there are no definite plans for XML parsing. This is partially due to the instability of the `xml5ever` crate, and uncertainty regarding whether XML parsing should be strict or lenient (which is prevailing design of the xml5ever crate, but maybe undesired by XML consumers). If there's any precedence for strict parsing, then I would need to find a separate compliant parser for XML which also adds some complexity to the codebase.

**Comment by ebebbington** [comment]
Ok thank you for the fast response :)
