### ISSUE TITLE
Publishing on JSR?

### ISSUE THREAD

**Issue by fabon-f** [b-fuze/deno-dom#164]
Is there any plans to publish this package on JSR?

One more question: there is already a package named [@b-fuze/deno-dom](https://jsr.io/@b-fuze/deno-dom) on JSR. Is it the package which a real author is publishing?  I can confirm that an owner of the scope `@b-fuze` in JSR is linked to GitHub account @b-fuze so it's probably not an impersonation, but if so it would be desirable to clarify the status of JSR support (maybe experimental?) in README not to raise a pointless security concerns.

**Comment by b-fuze** [comment]
@fabon-f yes, you are correct, thanks for the feedback. That package on JSR was published by me as an initial package around the time JSR was announced. I've since published [the latest Deno DOM to JSR](https://jsr.io/@b-fuze/deno-dom@0.1.47) and have also updated the Github README to reflect using Deno DOM via JSR instead of the older https://deno.land/x and will focus my future efforts on JSR
