### ISSUE TITLE
The safe alternative to eval() doesn't work on some cases

### ISSUE THREAD

**Issue by Hunam6** [b-fuze/deno-dom#34]
[See this ref first](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!)

A minimal reproducible example:
```typescript
import {DOMParser} from 'https://deno.land/x/deno_dom/deno-dom-wasm.ts'
const document = new DOMParser().parseFromString(
  `
  <div class='main'>
    <h1>Hello<span>world</span></h1>
  </div>
  `,
  'text/html'
)!
const selector = document.getElementsByClassName('main')
let bar = '.children[0]'
let foo = 0
console.log(eval('selector[0].children[foo]' + bar + '.textContent')) //work
console.log(Function('"use strict";return (selector[0].children[foo]' + bar + '.textContent)')()) //don't work
```
But as shown [here](https://jsfiddle.net/so5ckgb7), it should work.

**Comment by andreubotella** [comment]
This is not an issue with deno-dom, the error is because the function contents can't seem to find the outside variable `selector`. From a few quick tests, this is because Deno code runs in a module context (as if you were running a `<script type="module">` block in the browser), which apparently makes variable resolution stricter inside functions.

**Comment by Hunam6** [comment]
Okay but, is this a Deno issue too?
```typescript
console.log(Function('"use strict";return ('+selector+'[0].children['+foo+']' + bar + '.textContent)')())
```

**Comment by andreubotella** [comment]
No. It's due to a fundamental difference between JS code run as script (as with Node and with `<script>` elements in browsers) and JS code run as a module (as with `<script type="module">`). The fact that Deno uses a module context is what allows it to use the import/export machinery rather than something like `require()`.

**Comment by Hunam6** [comment]
Okay, I think I get it, so it's not a Deno bug either?

**Comment by 0kku** [comment]
That's right. Deno uses [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) for everything. The code you've shown relies on being executed in sloppy mode. `Function` constructor invoked in a strict context can't access its surrounding scope for security reasons. Instead, pass all the variables it needs to access as arguments to the function:
```ts
(new Function("selector", "foo", '"use strict";return (selector[0].children[foo]' + bar + '.textContent)'))(selector, foo)
```

This has nothing to do with deno-dom or Deno. It's a security feature of JS.
